services:
  n8n-chat:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WEBHOOK_URL=https://<webhook url>
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Example webhook URLs:

# For n8n Cloud: https://yourname.app.n8n.cloud/webhook/513107b3-6f3a-4a1e-af21-659f0ed14183

# For self-hosted: http://localhost:5678/webhook/513107b3-6f3a-4a1e-af21-659f0ed14183 