name: Test Application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run basic tests
      run: |
        # Test that the server starts
        timeout 10s npm start &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 5
        
        # Test health endpoint
        curl -f http://localhost:3000/health || exit 1
        
        # Test main page loads
        curl -f http://localhost:3000/ || exit 1
        
        # Cleanup
        kill $SERVER_PID || true

    - name: Lint and validate files
      run: |
        # Check if package.json is valid
        node -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8'))"
        
        # Check if HTML files are present
        test -f public/index.html
        test -f public/fullscreen.html
        
        # Check if server.js exists
        test -f server.js
        
        echo "All validation checks passed!"
